[application]

[web.app]

# HTML title tag content
title = "jp-web-novel-editor"

# include `assets` in web platform
[web.resource]

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
